# this parameter has no effect, see uk.gov.companieshouse.filingmock.Application.SLEEP_TIME
application.waitTimeMs=${CONSUMER_SLEEP_MS}

kafka.broker.address=${KAFKA3_BROKER_ADDR}

kafka.consumer.topic=${KAFKA_CONSUMER_TOPIC}
kafka.consumer.pollTimeout=${KAFKA_CONSUMER_TIMEOUT_MS}


kafka.api.url=${CHS_KAFKA_API_LOCAL_URL}/private/filing-processed

management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/chips-filing-mock
management.endpoints.web.path-mapping.health=/healthcheck
management.endpoint.health.enabled=true

# OpenTelemetry configuration
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
